name: Read Variable from File

on:
#   pull_request:
#     types:
#       - closed
#     branches:
#       - main
  push:
    # branches:
    #   - mainer


jobs:
  git-stuff-mac:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Local config
        run: |
          cat .git/config
      - name: Home config
        run: |
          cat ~/.gitconfig

  git-stuff-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Local config
        run: |
          cat .git/config
      - name: Home config
        run: |
          cat ~/.gitconfig


  build:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          # path: main
          # ref: build-${{ env.WORKFLOW_BUILD_NUMBER }}
      - name: Print Head Ref
        run: |
          echo "Head Ref: ${{ github.head_ref }}"
          echo "Base ref: ${{ github.base_ref }}"
      - name: Print event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event: ${{ github.event }}"
      - name: Print Commit SHA
        run: |
          echo "Commit sha that triggered action: ${{ github.sha }}"
      - name: Get PWD
        run: |
          pwd
          ls -la
          ls -la ../ 

      - name: Read variable from file
        run: |
          echo "Reading variable from file"
          TEST=$(cat variable.txt)
          TEST="TEST=$TEST"
          echo $TEST >> $GITHUB_ENV
          echo "ENV - "
          echo $GITHUB_ENV


  checkoutonly:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Print Head Ref
        run: |
          echo "Head Ref: ${{ github.head_ref }}"
          echo "Base ref: ${{ github.base_ref }}"
      - name: Print Commit SHA
        run: |
          echo "Commit sha that triggered action: ${{ github.sha }}"
      - name: Print event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event: ${{ github.event }}"



  merge-only: 
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Print Head Ref
        run: |
          echo "Head Ref: ${{ github.head_ref }}"
          echo "Base ref: ${{ github.base_ref }}"
      - name: Print Commit SHA
        run: |
          echo "Commit sha that triggered action: ${{ github.sha }}"
      - name: Print event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event: ${{ github.event }}"